# Generated by Django 4.2.3 on 2023-08-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="用例路径")),
                ("is_pass", models.BooleanField(default=False, verbose_name="测试通过")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "初始化"),
                            (1, "准备开始"),
                            (2, "正在执行"),
                            (3, "正在正常报告"),
                            (4, "执行完毕"),
                            (-1, "执行出错"),
                        ],
                        default=0,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
    ]
