# Generated by Django 4.2.3 on 2023-08-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_api", "0003_alter_case_project"),
        ("project", "0002_remove_project_user_project_pm_project_user_list"),
        ("case_ui", "0001_initial"),
        ("suite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runresult",
            name="project",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
        ),
        migrations.CreateModel(
            name="Suite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="套件名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="套件描述"),
                ),
                (
                    "case_api_list",
                    models.ManyToManyField(blank=True, to="case_api.case"),
                ),
                ("case_ui_list", models.ManyToManyField(blank=True, to="case_ui.case")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runresult",
            name="suite",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="suite.suite",
            ),
        ),
    ]
