# Generated by Django 4.2.3 on 2023-08-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_remove_project_user_project_pm_project_user_list"),
        ("suite", "0002_runresult_project_suite_runresult_suite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runresult",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="suite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suite.suite"
            ),
        ),
    ]
