# Generated by Django 4.2.3 on 2023-08-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suite", "0003_alter_runresult_project_alter_runresult_suite"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="cron",
            field=models.CharField(blank=True, max_length=20, verbose_name="cron表达式"),
        ),
        migrations.AddField(
            model_name="suite",
            name="hook_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="hook秘钥"),
        ),
        migrations.AddField(
            model_name="suite",
            name="run_type",
            field=models.CharField(
                choices=[("0", "ONCE"), ("C", "Cron"), ("w", "WebHook")],
                default="0",
                max_length=1,
                verbose_name="运行类型",
            ),
        ),
    ]
