# Generated by Django 4.2.3 on 2023-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suite", "0004_suite_cron_suite_hook_key_suite_run_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suite",
            name="hook_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="hook密钥"),
        ),
        migrations.AlterField(
            model_name="suite",
            name="run_type",
            field=models.CharField(
                choices=[("O", "单次执行"), ("C", "Cron"), ("W", "WebHook")],
                default="O",
                max_length=1,
                verbose_name="运行类型",
            ),
        ),
    ]
