# Generated by Django 4.2.3 on 2023-08-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0017_task_cluster_alter"),
        ("suite", "0005_alter_suite_hook_key_alter_suite_run_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_q.schedule",
            ),
        ),
    ]
