# Generated by Django 4.2.3 on 2023-10-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_api", "0003_alter_case_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endpoint",
            old_name="header",
            new_name="headers",
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="method",
            field=models.CharField(max_length=8, verbose_name="请求方法"),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="url",
            field=models.CharField(max_length=255, verbose_name="接口地址"),
        ),
    ]
