# Generated by Django 4.2.3 on 2023-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_profile_head_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="head_img",
            field=models.FileField(
                default=None,
                max_length=512,
                null=True,
                upload_to="",
                verbose_name="头像地址",
            ),
        ),
    ]
