# Generated by Django 4.2.3 on 2023-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_profile_head_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="head_img",
            field=models.CharField(default=2, max_length=512, verbose_name="头像地址"),
            preserve_default=False,
        ),
    ]
